/* Bank kuis Bab 2: 30 soal, 5 opsi A-E, C3-C6 + HOTS. */
(function(){
if(!window.LMS_DATA||!LMS_DATA.quiz)return;
LMS_DATA.quiz[2]=[
["Seorang siswa gagal mengikuti lomba yang telah dipersiapkannya selama berbulan-bulan. Berdasarkan QS Al-Baqarah/2:155–157, sikap yang paling tepat adalah …",["menyalahkan teman yang tidak mendukung","berhenti mengikuti kegiatan sekolah","mengucapkan istirja, menerima ketentuan Allah, dan tetap berusaha","menganggap kegagalan sebagai tanda Allah tidak menyayanginya","menyembunyikan kesedihan dengan berpura-pura tidak peduli"],2],
["Rina kehilangan sebagian uang tabungannya karena terkena musibah. Penerapan kandungan QS Al-Baqarah/2:155–157 yang paling tepat adalah …",["menuduh orang lain tanpa bukti","mengucapkan Inna lillahi wa inna ilaihi raji'un dan berusaha memperbaiki keadaan","menolak semua bantuan orang lain","merasa hidupnya tidak lagi berguna","membalas kerugian dengan mengambil milik orang lain"],1],
["Ketika mendapat komentar buruk dari orang lain mengenai agamanya, seorang muslim hendaknya menerapkan QS Ali 'Imran/3:186 dengan cara …",["membalas hinaan dengan hinaan","menyebarkan keburukan orang tersebut","diam tanpa melakukan apa pun","bersabar, bertakwa, dan tetap teguh menjalankan ajaran Allah","meninggalkan lingkungan masyarakat"],3],
["Seorang siswa memperoleh nilai sangat tinggi setelah belajar dengan sungguh-sungguh. Berdasarkan HR Muslim No. 5318, sikap yang tepat adalah …",["menyombongkan keberhasilannya","menganggap keberhasilan hanya karena kecerdasannya","bersyukur kepada Allah dan tetap rendah hati","meremehkan siswa yang nilainya rendah","berhenti belajar karena sudah berhasil"],2],
["Seorang pedagang mengalami kerugian besar. Ia tetap mencari solusi, berdoa, dan tidak menyalahkan Allah. Sikap tersebut menunjukkan bahwa sabar berarti …",["menerima keadaan tanpa usaha","menghindari semua masalah","menyerah terhadap keadaan","menghadapi ujian dengan keteguhan hati disertai ikhtiar","menunggu bantuan orang lain"],3],
["Ketika seseorang memperoleh nikmat kesehatan setelah sebelumnya sakit, berdasarkan HR Muslim No. 5318 sebaiknya ia …",["menganggap kesembuhan sebagai keberuntungan semata","bersyukur kepada Allah","memamerkan kesehatannya","melupakan pengalaman sakitnya","merasa tidak akan pernah sakit lagi"],1],
["Dalam QS Ali 'Imran/3:186, dua sikap yang harus menyertai seorang mukmin ketika menghadapi ujian adalah …",["sabar dan takwa","kaya dan terkenal","diam dan pasrah","berani dan keras","sedih dan takut"],0],
["Seorang siswa mengalami kesulitan ekonomi sehingga fasilitas belajarnya terbatas. Tindakan yang paling sesuai dengan nilai sabar adalah …",["menghindari pelajaran yang sulit","menyalahkan keadaan keluarga","tetap belajar dengan sabar dan mencari solusi yang memungkinkan","berhenti sekolah","membandingkan dirinya dengan siswa yang lebih mampu"],2],
["QS Al-Baqarah/2:155 menyebut beberapa bentuk cobaan berupa ketakutan, kelaparan, kekurangan harta, jiwa, dan buah-buahan. Kesamaan dari berbagai cobaan tersebut adalah …",["hanya dialami orang miskin","hanya dialami orang yang berdosa","merupakan bagian dari kehidupan manusia dan menguji kesabaran","selalu menyebabkan seseorang kehilangan iman","dapat dihindari jika seseorang memiliki banyak harta"],2],
["Dua siswa menghadapi kegagalan yang sama. Siswa A berkata, ‘Ini pasti akhir dari semuanya.’ Siswa B berkata, ‘Aku akan menerima hasil ini, mengevaluasi kesalahan, lalu mencoba lagi.’ Perbedaan utama keduanya adalah …",["Siswa A lebih berani daripada B","Siswa B menerapkan sabar yang disertai ikhtiar","Siswa A lebih religius daripada B","Siswa B tidak menerima ketentuan Allah","keduanya menunjukkan sikap sabar yang sama"],1],
["Seseorang kehilangan anggota keluarganya. Ia mengucapkan istirja, tetapi setelah itu tetap berusaha mengurus keluarga yang ditinggalkan. Analisis yang paling tepat terhadap perilaku tersebut adalah …",["ia belum menerima musibah","ia tidak benar-benar bersabar","ia memadukan penerimaan terhadap ketentuan Allah dengan tanggung jawab dan ikhtiar","ia melupakan rasa sedihnya","ia menganggap musibah sebagai sesuatu yang tidak penting"],2],
["QS Ali 'Imran/3:186 menyatakan bahwa orang beriman akan diuji dalam harta dan dirinya serta mendengar perkataan yang menyakitkan. Pesan penting dari ayat tersebut adalah …",["kehidupan orang beriman pasti bebas masalah","ujian hanya terjadi karena kelemahan seseorang","seorang mukmin perlu memiliki kesiapan mental menghadapi berbagai bentuk ujian","hinaan harus selalu dibalas","masalah kehidupan tidak perlu dipikirkan"],2],
["HR Tirmizi No. 2322 menjelaskan bahwa manusia yang paling berat ujiannya adalah para nabi, kemudian orang-orang yang memiliki keutamaan setelah mereka. Dari kandungan tersebut dapat dianalisis bahwa …",["beratnya ujian selalu menunjukkan seseorang dibenci Allah","orang saleh tidak pernah mengalami kesulitan","ujian dapat menjadi sarana peningkatan kualitas iman dan kedekatan kepada Allah","semakin banyak masalah berarti semakin buruk seseorang","orang beriman harus mencari kesulitan sebanyak-banyaknya"],2],
["HOTS: Andi melihat temannya mendapat beasiswa, sedangkan dirinya tidak. Ia berkata, ‘Allah tidak adil kepada saya.’ Berdasarkan kandungan Bab II, kesalahan cara berpikir Andi adalah …",["menganggap rezeki hanya berasal dari usaha manusia","tidak memahami bahwa kehidupan manusia mengandung berbagai bentuk ujian","menganggap pendidikan bukan bagian dari kehidupan","terlalu banyak bersyukur","terlalu rajin berusaha"],1],
["HOTS: Seorang siswa mengalami kegagalan akademik berkali-kali. Ia tetap belajar, memperbaiki metode belajar, meminta bimbingan guru, dan berdoa. Perilaku tersebut menunjukkan bahwa …",["sabar hanya berupa ketenangan hati","sabar berarti menunggu tanpa tindakan","sabar dapat menjadi kekuatan untuk menghadapi ujian sekaligus mendorong ikhtiar","kegagalan harus diterima tanpa evaluasi","usaha manusia tidak berhubungan dengan kesabaran"],2],
["Dalam HR Muslim No. 5318 dijelaskan bahwa seorang mukmin berada dalam keadaan baik ketika mendapat kesenangan maupun musibah. Hal ini terjadi karena …",["ia tidak pernah merasakan kesedihan","ia selalu memperoleh keuntungan duniawi","ia bersyukur ketika memperoleh nikmat dan bersabar ketika tertimpa musibah","ia menghindari semua risiko kehidupan","ia tidak memiliki masalah kehidupan"],2],
["HOTS: Seseorang berkata, ‘Kalau ujian itu pasti datang, berarti manusia tidak perlu melakukan pencegahan.’ Berdasarkan Bab II, argumen tersebut tidak tepat karena …",["semua masalah pasti dapat dihindari","sabar berarti pasif","kesabaran harus berjalan bersama usaha menghadapi masalah","manusia tidak boleh menerima takdir","ujian hanya berlaku bagi orang tertentu"],2],
["Seorang siswa mendapat kritik dari gurunya. Ia marah, meninggalkan kelas, dan menyebarkan keburukan gurunya di media sosial. Penilaian paling tepat terhadap tindakan tersebut adalah …",["benar karena kritik harus dibalas","kurang tepat karena tidak mencerminkan sabar dan takwa","benar karena mempertahankan harga diri","tepat karena masalah harus diumumkan","netral karena setiap orang bebas bereaksi"],1],
["Manakah tindakan berikut yang paling mencerminkan pemahaman mendalam terhadap sabar?",["menerima semua keadaan tanpa usaha","menahan emosi, menerima ketentuan Allah, lalu mencari solusi","menghindari setiap keadaan yang berisiko","tidak mengungkapkan perasaan kepada siapa pun","menyerahkan semua persoalan kepada orang lain"],1],
["HOTS: Dua orang sama-sama kehilangan pekerjaan. Orang pertama menganggap dirinya gagal dan berhenti berusaha. Orang kedua menerima keadaan, memperbanyak doa, meningkatkan keterampilan, dan mencari pekerjaan baru. Penilaian yang paling tepat adalah …",["keduanya sama-sama tidak sabar","orang pertama lebih sabar karena tidak banyak bertindak","orang kedua lebih mencerminkan sabar karena disertai ikhtiar","orang pertama lebih bertawakal","keduanya tidak mengalami ujian"],2],
["Pernyataan berikut yang paling tepat untuk menilai hubungan antara sabar dan takwa dalam QS Ali 'Imran/3:186 adalah …",["sabar saja sudah cukup","takwa tidak diperlukan ketika menghadapi ujian","sabar dan takwa menjadi sikap utama dalam menghadapi ujian","takwa hanya diperlukan ketika memperoleh nikmat","sabar hanya berkaitan dengan masalah ekonomi"],2],
["HOTS: Sebuah sekolah membuat program pendampingan bagi siswa yang mengalami kesulitan belajar. Program tersebut menyediakan bimbingan, dukungan teman sebaya, dan kesempatan memperbaiki hasil belajar. Program tersebut sesuai dengan Bab II karena …",["mengajarkan siswa untuk menghindari ujian","membantu siswa menghadapi ujian dengan sabar sekaligus melakukan ikhtiar","membuat siswa tidak perlu berusaha sendiri","menghilangkan semua cobaan kehidupan","menjamin semua siswa memperoleh hasil yang sama"],1],
["Pujian kepada seseorang dapat menjadi baik apabila …",["diberikan sebanyak-banyaknya","membuat orang tersebut merasa lebih tinggi dari orang lain","mendorongnya untuk meningkatkan amal dan konsistensi dalam kebaikan tanpa berlebihan","diberikan agar orang lain iri","digunakan untuk mendapatkan keuntungan pribadi"],2],
["HOTS: Seorang siswa berkata kepada temannya yang sedang berduka, ‘Orang sabar itu tidak boleh menangis.’ Evaluasi terhadap nasihat tersebut adalah …",["sepenuhnya benar karena menangis berarti tidak sabar","benar karena kesedihan dilarang dalam Islam","kurang tepat karena sabar tidak berarti kehilangan perasaan, tetapi mampu menghadapi musibah dengan sikap yang benar","salah karena semua bentuk kesedihan harus dilampiaskan","benar karena kesabaran berarti tidak boleh berbicara"],2],
["Seorang guru meminta siswa membuat program untuk membantu teman yang mengalami kesulitan belajar. Rancangan yang paling sesuai dengan nilai sabar adalah …",["memberikan jawaban tugas kepada teman","meminta teman berhenti mengikuti pelajaran","membuat kelompok belajar, pendampingan, evaluasi berkala, dan motivasi","membiarkan teman belajar sendiri","menggantikan semua tugas teman"],2],
["HOTS: Kamu diminta membuat kampanye digital bertema ‘Sabar Menghadapi Cobaan’. Konsep yang paling sesuai dengan QS Al-Baqarah/2:155–157 adalah …",["Hidup tanpa masalah jika selalu berdoa","Musibah adalah tanda Allah membenci manusia","Ketika diuji: istirja, sabar, tetap berikhtiar, dan berharap rahmat Allah","Tidak perlu berusaha karena semua sudah ditentukan","Orang kuat adalah orang yang tidak pernah menangis"],2],
["Jika kamu diminta menyusun langkah penyelesaian masalah berdasarkan QS Ali 'Imran/3:186, urutan yang paling tepat adalah …",["marah → membalas → menyerah → berdoa","menghindar → diam → melupakan → selesai","menghadapi ujian → bersabar → bertakwa → tetap menjalankan kebaikan","membalas → mencari dukungan → menyalahkan orang lain","mengeluh → menyerah → menunggu pertolongan"],2],
["HOTS: Kelasmu ingin membuat kegiatan ‘Pekan Sabar’. Agar kegiatan tersebut mencerminkan Bab II, rancangan terbaik adalah …",["lomba siapa yang paling lama diam","seminar tentang cara menghindari masalah","kajian ayat dan hadis, studi kasus, refleksi pengalaman, serta proyek penerapan sabar","kegiatan hiburan tanpa pembahasan agama","lomba menceritakan masalah pribadi tanpa solusi"],2],
["HOTS: Kamu diminta membuat solusi bagi siswa yang mengalami tekanan karena kegagalan akademik. Kegiatan yang paling mencerminkan konsep sabar adalah …",["poster ‘Jangan pernah gagal’","kelompok pendampingan yang menggabungkan doa, refleksi, evaluasi kesalahan, dan perencanaan usaha berikutnya","kegiatan untuk menyalahkan guru","meminta siswa melupakan kegagalannya","memberikan nilai tambahan tanpa memperbaiki proses belajar"],1],
["HOTS: Sebuah kelompok siswa menghadapi kegagalan dalam proyek sekolah dan mulai saling menyalahkan. Jika kamu menjadi ketua kelompok, tindakan yang paling mencerminkan kandungan Bab II adalah …",["mencari anggota yang paling bersalah dan mengeluarkannya","membatalkan proyek dan menyalahkan keadaan","mengajak anggota melakukan refleksi, menerima kegagalan, memperbaiki kesalahan, membagi tugas kembali, dan melanjutkan usaha","menyerahkan seluruh tanggung jawab kepada guru","mengabaikan masalah agar konflik berhenti"],2]
];
})();
