window.MATERIALS = {
1: {
 judul:'Hidup Sederhana Sesuai Tuntunan Agama',
 tujuan:['Menjelaskan makna hidup sederhana, israf, tabzir, dan kikir.','Menganalisis pesan QS Al-Furqan/25:67, QS Al-Isra/17:26–30, QS Al-Qasas/28:79–82, QS Al-Baqarah/2:177, dan QS Al-Ma’un/107:1–7.','Menunjukkan hubungan antara pengelolaan harta, kepedulian sosial, syukur, dan ketakwaan.','Menerapkan pola hidup sederhana dalam penggunaan uang, makanan, waktu, teknologi, dan fasilitas sekolah.'],
 pengantar:'Hidup sederhana dalam Islam bukan berarti hidup tanpa menikmati nikmat Allah. Kesederhanaan berarti menempatkan sesuatu secara proporsional: memenuhi kebutuhan secara halal, tidak berlebih-lebihan, tidak menyia-nyiakan nikmat, dan tidak menahan hak orang lain. Prinsip ini membentuk pribadi yang mampu mengendalikan keinginan, bersyukur, mandiri, dan peduli kepada sesama.',
 peta:'Nikmat Allah → kesadaran diri → pengendalian keinginan → penggunaan harta secara proporsional → berbagi → keberkahan dan ketenangan.',
 subbab:[
  ['1. Apa yang dimaksud hidup sederhana?','Sederhana adalah menggunakan sesuatu sesuai kebutuhan, kemampuan, manfaat, dan tujuan yang benar. Seseorang boleh memiliki barang yang baik dan menikmati rezeki, tetapi tidak menjadikan kemewahan sebagai ukuran harga diri. Kesederhanaan juga mencakup cara menggunakan waktu, tenaga, makanan, pakaian, uang, kendaraan, gawai, dan media sosial.','Contoh: membeli buku karena dibutuhkan untuk belajar lebih utama daripada membeli barang hanya karena mengikuti tren.'],
  ['2. Israf, tabzir, dan kikir','Israf adalah sikap melampaui batas dalam menggunakan sesuatu. Tabzir berkaitan dengan pemborosan atau penggunaan harta secara sia-sia dan tidak pada tempatnya. Kikir adalah enggan mengeluarkan harta pada kebutuhan yang benar atau menunaikan hak yang seharusnya diberikan. Ketiganya sama-sama menunjukkan kegagalan mengendalikan diri, meskipun bentuknya berbeda.','Kunci membedakannya: israf = berlebihan; tabzir = menyia-nyiakan; kikir = menahan secara tidak semestinya.'],
  ['3. QS Al-Furqan/25:67 — keseimbangan dalam membelanjakan harta','Ayat ini menggambarkan karakter hamba Allah dalam membelanjakan harta: tidak berlebihan dan tidak pula kikir, tetapi mengambil jalan tengah. Pesan utamanya bukan sekadar mengurangi pengeluaran, melainkan membangun kemampuan menentukan prioritas.','Penerapan pelajar: pisahkan kebutuhan pokok, kebutuhan belajar, tabungan, dan sedekah sebelum membelanjakan uang untuk keinginan.'],
  ['4. QS Al-Isra/17:26–30 — hak keluarga dan larangan pemborosan','Ayat-ayat ini menghubungkan pengelolaan harta dengan tanggung jawab sosial. Kerabat dan pihak yang membutuhkan memiliki hak untuk diperhatikan. Pada saat yang sama, pemborosan dilarang. Artinya, harta harus dikelola dengan tujuan yang baik, bukan sekadar dihabiskan.','Pertanyaan penting: apakah pengeluaran saya memberi manfaat nyata, atau hanya mengikuti gengsi dan dorongan sesaat?'],
  ['5. QS Al-Qasas/28:79–82 — pelajaran dari Qarun','Kisah Qarun menunjukkan bahaya ketika kekayaan melahirkan kesombongan. Sebagian manusia terpukau oleh kemegahan, tetapi orang yang berilmu memahami bahwa pahala Allah lebih baik daripada sekadar kemewahan dunia. Harta yang tidak disertai syukur dan tanggung jawab dapat berubah menjadi sumber kebinasaan.','Pelajaran: keberhasilan tidak diukur hanya dari apa yang dimiliki, tetapi dari cara memperoleh, menggunakan, dan mempertanggungjawabkannya.'],
  ['6. QS Al-Baqarah/2:177 — kesalehan tidak berhenti pada simbol','Ayat ini menjelaskan bahwa kebajikan bukan hanya persoalan bentuk lahiriah, tetapi mencakup iman, kepedulian kepada kerabat, anak yatim, orang miskin, musafir, dan mereka yang membutuhkan. Pengelolaan harta menjadi bagian dari kesalehan ketika diarahkan untuk kebaikan.','Sederhana dan dermawan dapat berjalan bersama: seseorang mengurangi kemewahan pribadi agar memiliki ruang lebih besar untuk berbagi.'],
  ['7. QS Al-Ma’un/107:1–7 — kepedulian sosial','Surah Al-Ma’un mengkritik perilaku keagamaan yang tidak melahirkan kepedulian kepada yatim, miskin, dan orang yang membutuhkan bantuan. Ibadah seharusnya membentuk karakter sosial. Kesederhanaan bukan hanya urusan pribadi, tetapi juga membuka kesempatan untuk membantu orang lain.','Latihan: pilih satu bentuk bantuan sederhana yang dapat dilakukan tanpa menunggu memiliki banyak uang.'],
  ['8. Hadis tentang tidak berlebih-lebihan dan keutamaan memberi','Hadis-hadis pada bab ini menegaskan larangan berlebihan serta pentingnya kemampuan mencukupi kebutuhan dan memberi. Prinsip konsumsi Islam tidak membenarkan hidup boros, tetapi juga tidak memerintahkan seseorang menelantarkan kebutuhan diri dan keluarga.','Rumus praktis: halal → perlu → bermanfaat → proporsional → ada ruang untuk berbagi.'],
  ['9. Kesalahan yang sering terjadi','Kesederhanaan kadang disalahpahami sebagai tidak boleh memiliki barang bagus; sebaliknya, gaya hidup konsumtif dianggap sebagai tanda keberhasilan. Kedua pandangan tersebut perlu dikoreksi. Ukuran yang lebih tepat adalah manfaat, kewajaran, kemampuan, dan dampak terhadap diri serta orang lain.','Waspadai belanja karena FOMO, pamer di media sosial, utang konsumtif, membuang makanan, dan membeli barang yang jarang dipakai.'],
  ['10. Penerapan dalam kehidupan pelajar','Buat anggaran uang saku mingguan; tentukan batas pembelian jajan; gunakan seragam dan buku dengan baik; hemat air dan listrik; batasi pembelian karena tren; sisihkan sebagian rezeki untuk infak; dan biasakan bertanya sebelum membeli: “Apakah ini kebutuhan atau sekadar keinginan?”','Tantangan 7 hari: catat semua pengeluaran, beri tanda K untuk kebutuhan dan I untuk keinginan, lalu evaluasi tiga pengeluaran yang dapat diperbaiki.']
 ],
 hikmah:'Kesederhanaan melatih kebebasan dari belenggu keinginan. Orang yang mampu mengendalikan konsumsi lebih mudah bersyukur, menolong orang lain, dan menggunakan nikmat sebagai sarana mendekat kepada Allah.'
},
2:{
 judul:'Sabar dalam Menghadapi Cobaan',
 tujuan:['Menjelaskan pengertian sabar dan bentuk-bentuk ujian kehidupan.','Menganalisis QS Al-Baqarah/2:155–157 dan QS Ali Imran/3:186.','Memahami hubungan sabar dengan ikhtiar, doa, tawakal, syukur, dan takwa.','Menerapkan strategi menghadapi kegagalan, kehilangan, tekanan belajar, konflik, dan kesulitan hidup secara Islami.'],
 pengantar:'Cobaan merupakan bagian dari kehidupan manusia. Al-Qur’an tidak menjanjikan bahwa orang beriman akan terbebas dari masalah, tetapi memberikan cara untuk menghadapinya. Sabar berarti tetap menjaga ketaatan dan sikap yang benar ketika menghadapi tekanan. Sabar tidak sama dengan menyerah; ia berjalan bersama ikhtiar, doa, evaluasi, dan tawakal.',
 peta:'Cobaan → kesadaran bahwa hidup adalah ujian → sabar + ikhtiar + doa → tawakal → belajar dari pengalaman → ketangguhan dan kedewasaan iman.',
 subbab:[
  ['1. Makna sabar','Sabar adalah kemampuan menahan diri agar tidak bereaksi secara salah ketika menghadapi kesulitan. Sabar mencakup keteguhan dalam taat, kemampuan meninggalkan maksiat, dan kemampuan menghadapi musibah dengan sikap yang benar.','Sabar bukan berarti tidak boleh sedih atau menangis. Yang dijaga adalah ucapan, keputusan, dan perilaku agar tidak keluar dari prinsip agama.'],
  ['2. Bentuk-bentuk cobaan','QS Al-Baqarah/2:155 menyebut antara lain rasa takut, kelaparan, kekurangan harta, jiwa, dan hasil. Dalam kehidupan pelajar, bentuknya dapat berupa nilai yang turun, kegagalan lomba, konflik pertemanan, kehilangan, masalah keluarga, tekanan ekonomi, atau kegagalan mencapai target.','Ujian setiap orang berbeda. Karena itu, membandingkan penderitaan secara kasar justru dapat mengurangi empati.'],
  ['3. QS Al-Baqarah/2:155–157 — respons saat musibah','Ayat ini menyatakan bahwa ujian akan terjadi dan memberikan kabar gembira bagi orang-orang yang sabar. Saat musibah datang, orang beriman mengingat Allah dan mengucapkan istirja’ (inna lillahi wa inna ilaihi raji’un), menyadari bahwa dirinya dan apa yang dimiliki berada dalam kepemilikan Allah.','Pesan penting: musibah tidak otomatis berarti Allah membenci seseorang. Yang dinilai adalah bagaimana manusia merespons dan mengambil pelajaran.'],
  ['4. QS Ali Imran/3:186 — sabar dan takwa','Ayat ini mengingatkan bahwa harta dan diri dapat menjadi bahan ujian, termasuk gangguan dari orang lain. Di akhir pesan, kesabaran dihubungkan dengan ketakwaan. Jadi, keteguhan bukan sekadar menahan emosi, tetapi tetap memilih tindakan yang benar.','Jika diejek, jangan membalas dengan penghinaan. Tetap tegas, cari bantuan, dan gunakan cara yang bermartabat.'],
  ['5. Sabar berbeda dari pasrah tanpa usaha','Pasrah tanpa usaha berarti berhenti melakukan ikhtiar dengan alasan “sudah takdir”. Sabar justru menuntut ketekunan. Seorang siswa yang gagal ujian tidak cukup berkata “saya sabar”; ia perlu mencari penyebab, memperbaiki cara belajar, meminta bimbingan, lalu menyerahkan hasil kepada Allah.','Rumus: terima kenyataan → tenangkan diri → cari penyebab → susun ikhtiar → berdoa → tawakal → evaluasi.'],
  ['6. Hadis tentang keadaan orang beriman','Hadis riwayat Muslim menjelaskan keistimewaan orang beriman: ketika memperoleh kesenangan ia bersyukur, dan ketika tertimpa kesulitan ia bersabar. Dua keadaan tersebut sama-sama dapat menjadi kebaikan baginya.','Karena itu, keberhasilan membutuhkan syukur agar tidak sombong, sedangkan kesulitan membutuhkan sabar agar tidak putus asa.'],
  ['7. Hadis tentang beratnya ujian','Hadis riwayat Tirmizi menjelaskan bahwa manusia yang paling berat ujiannya adalah para nabi, kemudian orang-orang yang memiliki keutamaan setelah mereka. Ini mengajarkan bahwa beratnya ujian tidak selalu menjadi ukuran rendahnya kedudukan seseorang di sisi Allah.','Jangan menyimpulkan “saya diuji berarti saya gagal”. Ujian dapat menjadi sarana pembentukan keteguhan, penghapusan kesalahan, dan peningkatan kualitas diri.'],
  ['8. Sabar dalam belajar','Sabar akademik berarti mampu bertahan dalam proses yang panjang: membaca, mengulang, bertanya, berlatih, menerima koreksi, dan memperbaiki kesalahan. Nilai rendah seharusnya menjadi data untuk evaluasi, bukan alasan untuk menyerah.','Gunakan target kecil: satu materi, satu latihan, satu evaluasi. Kemajuan kecil yang konsisten lebih kuat daripada semangat sesaat.'],
  ['9. Sabar dalam konflik sosial','Dalam konflik, sabar bukan berarti membiarkan kezaliman. Sabar berarti mengendalikan emosi sambil mencari penyelesaian yang adil. Dengarkan pihak lain, bedakan fakta dari asumsi, hindari menyebarkan masalah di media sosial, dan libatkan guru/orang dewasa jika diperlukan.','Pilih kalimat yang memperbaiki masalah, bukan kalimat yang hanya melampiaskan kemarahan.'],
  ['10. Latihan ketangguhan 7 hari','Setiap hari tuliskan satu kesulitan, respons spontan yang muncul, respons yang lebih baik, dan ikhtiar yang dapat dilakukan. Akhiri dengan doa dan satu hal yang disyukuri.','Tujuan latihan bukan menghilangkan masalah, tetapi melatih pola respons yang lebih tenang, realistis, dan bertanggung jawab.']
 ],
 hikmah:'Sabar membuat seseorang tidak dikendalikan oleh keadaan. Ia memberi jarak antara masalah dan reaksi sehingga manusia dapat memilih tindakan yang lebih bijaksana.'
},
3:{
 judul:'Menjaga Kelestarian Lingkungan',
 tujuan:['Menjelaskan hubungan manusia, alam, dan amanah kekhalifahan.','Menganalisis QS Ar-Rum/30:41–42, QS Al-A’raf/7:56–58, QS Sad/38:27, QS Al-Furqan/25:45–50, QS Al-Baqarah/2:204–206, dan hadis tentang menanam.','Mengidentifikasi bentuk kerusakan lingkungan di sekitar madrasah dan rumah.','Merancang aksi sederhana untuk menjaga kebersihan, menghemat sumber daya, dan merawat lingkungan.'],
 pengantar:'Islam memandang bumi sebagai amanah. Manusia memperoleh manfaat dari air, tanah, tumbuhan, hewan, udara, dan berbagai sumber daya, tetapi pemanfaatan tersebut harus disertai tanggung jawab. Menjaga lingkungan bukan sekadar program kebersihan; ia berkaitan dengan syukur, amanah, kemaslahatan, dan larangan membuat kerusakan.',
 peta:'Nikmat alam → amanah khalifah → larangan merusak → penggunaan berkelanjutan → kepedulian bersama → lingkungan sehat dan kehidupan yang maslahat.',
 subbab:[
  ['1. Manusia sebagai khalifah di bumi','Khalifah mengandung tanggung jawab untuk mengelola bumi dengan ilmu dan amanah. Manusia bukan pemilik mutlak yang bebas berbuat apa saja. Setiap pemanfaatan harus mempertimbangkan dampaknya bagi generasi sekarang, generasi mendatang, dan makhluk lain.','Contoh: mengambil air secukupnya, menjaga pohon, dan tidak membuang limbah ke sungai merupakan bentuk tanggung jawab sederhana.'],
  ['2. QS Ar-Rum/30:41–42 — kerusakan akibat perbuatan manusia','Ayat ini mengarahkan manusia memperhatikan bahwa kerusakan di darat dan laut berkaitan dengan perbuatan manusia. Kerusakan menjadi peringatan agar manusia kembali kepada jalan yang benar dan memperbaiki perilaku.','Makna pendidikan: lingkungan dapat menjadi cermin dari perilaku manusia. Jika budaya boros dan tidak peduli dibiarkan, dampaknya akan kembali kepada kehidupan manusia.'],
  ['3. QS Al-A’raf/7:56–58 — jangan membuat kerusakan','Ayat ini melarang membuat kerusakan di bumi setelah adanya perbaikan, sekaligus mengajarkan berdoa dengan rasa takut dan harap. Gambaran tanah yang baik dan tanah yang buruk mengingatkan bahwa kondisi lingkungan memengaruhi hasil kehidupan.','Tugas pelajar: jangan hanya membersihkan ketika ada lomba. Bangun kebiasaan menjaga lingkungan setiap hari.'],
  ['4. QS Sad/38:27 — ciptaan Allah tidak sia-sia','Ayat ini mengajak manusia menyadari bahwa penciptaan langit, bumi, dan segala yang ada memiliki hikmah. Cara pandang tersebut melahirkan penghormatan terhadap alam dan mendorong manusia mencari manfaat tanpa merusak keseimbangan.','Belajar lingkungan berarti juga belajar membaca tanda-tanda kebesaran Allah melalui keteraturan alam.'],
  ['5. QS Al-Furqan/25:45–50 — tanda-tanda kekuasaan Allah di alam','Rangkaian ayat ini mengajak memperhatikan bayangan, matahari, tidur, malam, siang, angin, dan hujan. Alam bukan sekadar latar kehidupan, tetapi sumber pelajaran tentang keteraturan dan rahmat Allah.','Hujan, air, cahaya matahari, dan tumbuhan dapat dipelajari sebagai sistem yang saling berhubungan.'],
  ['6. QS Al-Baqarah/2:204–206 — jangan menjadi perusak','Ayat ini menggambarkan orang yang pandai berbicara tetapi ketika berkuasa justru berusaha membuat kerusakan, merusak tanaman dan keturunan. Pesannya penting untuk membedakan antara ucapan yang baik dan tindakan yang benar-benar membawa maslahat.','Integritas lingkungan berarti apa yang kita katakan tentang kebersihan harus tampak dalam kebiasaan kita.'],
  ['7. Hadis tentang menanam','Hadis riwayat Bukhari-Muslim dari Anas bin Malik menjelaskan keutamaan menanam: hasil tanaman yang dimanfaatkan manusia, hewan, atau burung menjadi sedekah bagi penanamnya. Ini menunjukkan bahwa manfaat ekologis dapat bernilai ibadah.','Menanam bukan hanya aktivitas fisik; ia menjadi amal ketika dilakukan dengan niat baik dan dirawat dengan tanggung jawab.'],
  ['8. Bentuk kerusakan yang dekat dengan siswa','Sampah berserakan, pemborosan air, lampu dan AC menyala tanpa kebutuhan, penggunaan plastik berlebihan, vandalisme, perusakan tanaman, dan membuang limbah sembarangan adalah masalah nyata yang dapat dimulai dari lingkungan sekolah.','Mulailah dari masalah yang dapat diamati dan diukur, bukan hanya slogan besar.'],
  ['9. Prinsip 5R untuk tindakan nyata','Refuse (menolak barang yang tidak perlu), Reduce (mengurangi), Reuse (menggunakan kembali), Recycle (mendaur ulang), dan Recover/Repair (memulihkan atau memperbaiki). Prinsip ini membantu siswa mengubah kepedulian menjadi kebiasaan.','Pilih satu prinsip yang paling mudah dilakukan di kelas, lalu ukur hasilnya selama satu minggu.'],
  ['10. Proyek audit lingkungan madrasah','Kelompokkan siswa untuk mengamati sampah, air, listrik, tanaman, dan kebersihan. Catat kondisi awal, tentukan satu masalah prioritas, buat solusi, laksanakan selama satu minggu, lalu bandingkan kondisi sebelum dan sesudah.','Produk proyek: tabel pengamatan + foto kondisi (bila diizinkan) + rencana aksi + refleksi hasil.']
 ],
 hikmah:'Menjaga lingkungan adalah bentuk syukur yang terlihat. Ketika manusia merawat bumi, manfaatnya dapat dinikmati banyak makhluk dan lintas generasi.'
},
4:{
 judul:'Dakwah Penuh Hikmah',
 tujuan:['Menjelaskan pengertian, tujuan, dan ruang lingkup dakwah.','Menganalisis QS An-Nahl/16:125, QS Asy-Syu’ara/26:214–216, QS Al-Hijr/15:94–96, dan hadis riwayat Muslim dari Abu Hurairah.','Membedakan dakwah bil-hikmah, nasihat yang baik, dan dialog yang terbaik.','Menerapkan etika dakwah dalam kehidupan sekolah, keluarga, organisasi, dan media digital.'],
 pengantar:'Dakwah berarti mengajak manusia menuju kebaikan dan jalan Allah. Dakwah tidak hanya dilakukan melalui ceramah. Sikap jujur, membantu teman, membuat konten edukatif, menulis pesan yang baik, dan memberi teladan juga dapat menjadi bagian dari dakwah. Karena dakwah berhubungan dengan manusia, cara penyampaian sangat menentukan apakah pesan menjadi jembatan kebaikan atau justru menimbulkan penolakan.',
 peta:'Ilmu dan niat → memahami mad’u → memilih cara yang tepat → hikmah + nasihat baik + dialog terbaik → keteladanan → konsistensi → perubahan positif.',
 subbab:[
  ['1. Pengertian dan tujuan dakwah','Dakwah adalah usaha mengajak manusia kepada iman, kebaikan, dan kehidupan yang diridai Allah. Tujuannya bukan memenangkan perdebatan atau mempermalukan orang lain, tetapi membantu manusia mengenal kebenaran dan terdorong melakukan kebaikan.','Karena tujuan dakwah adalah perbaikan, metode dakwah harus sejalan dengan tujuan tersebut.'],
  ['2. Dakwah sebagai tanggung jawab bersama','Setiap orang dapat berkontribusi sesuai ilmu dan kemampuannya. Namun, menyampaikan agama tetap membutuhkan kehati-hatian: bedakan pengetahuan yang benar-benar dikuasai dengan hal yang belum diketahui. Jika belum tahu, bertanya kepada guru atau ahli adalah sikap ilmiah.','Dakwah yang baik tidak dibangun dari “katanya”, apalagi dari informasi yang belum diperiksa.'],
  ['3. QS An-Nahl/16:125 — tiga prinsip komunikasi dakwah','Ayat ini memuat prinsip hikmah, nasihat yang baik, dan dialog dengan cara terbaik. Hikmah berarti memilih pendekatan yang tepat; nasihat yang baik menyentuh hati tanpa merendahkan; dialog terbaik berarti membahas perbedaan dengan cara yang bermartabat.','Pertanyaan sebelum berbicara: siapa yang diajak, apa kebutuhannya, kapan waktunya, bahasa apa yang sesuai, dan apa tujuan pembicaraan?'],
  ['4. Makna bil-hikmah','Bil-hikmah bukan sekadar berbicara lembut. Hikmah mencakup ketepatan isi, metode, waktu, bahasa, dan pertimbangan terhadap kondisi orang yang menerima pesan. Tegas dapat tetap menjadi hikmah bila tepat, adil, dan tidak zalim.','Contoh: menegur teman yang membuang sampah sebaiknya dilakukan dengan cara yang membuatnya memahami alasan dan terdorong memperbaiki perilaku.'],
  ['5. QS Asy-Syu’ara/26:214–216 — memulai dari lingkungan terdekat','Ayat ini memerintahkan pemberian peringatan kepada kerabat yang dekat. Pesannya dapat diterapkan dengan membangun dakwah mulai dari diri sendiri dan lingkungan terdekat. Dakwah menjadi kuat ketika pendakwah menunjukkan keteladanan.','Sebelum mengajak teman disiplin, latih diri untuk disiplin. Sebelum mengajak santun, gunakan bahasa santun.'],
  ['6. QS Al-Hijr/15:94–96 — berani menyampaikan dan teguh','Ayat ini memerintahkan penyampaian secara terbuka dan mengingatkan adanya gangguan dari orang yang mencemooh. Dakwah membutuhkan keberanian sekaligus keteguhan. Namun keberanian tidak identik dengan kasar; keteguhan tetap harus dibarengi akhlak.','Jika mendapat komentar negatif, fokus pada substansi, jangan membalas penghinaan dengan penghinaan.'],
  ['7. Hadis Muslim dari Abu Hurairah — menunjukkan jalan kebaikan','Hadis ini menjelaskan bahwa orang yang menunjukkan kepada kebaikan memperoleh pahala seperti orang yang mengerjakannya, tanpa mengurangi pahala pelaku. Pesan ini menegaskan besarnya nilai menjadi perantara kebaikan.','Berbagi tutorial belajar, mengajak teman salat, mengingatkan dengan santun, atau membuat konten bermanfaat dapat menjadi jalan kebaikan.'],
  ['8. Etika dakwah tatap muka','Dengarkan sebelum menilai; gunakan bahasa yang jelas; hindari mempermalukan; bedakan kritik terhadap perilaku dan serangan terhadap pribadi; jangan memaksa; berikan contoh; dan pilih waktu yang tepat. Ketika masalah sensitif, percakapan pribadi sering lebih baik daripada menegur di depan banyak orang.','Tujuan teguran adalah memperbaiki, bukan mempertontonkan kesalahan seseorang.'],
  ['9. Dakwah di media digital','Media sosial memperluas jangkauan dakwah sekaligus memperbesar risiko salah informasi. Periksa sumber, tanggal, konteks, dan keaslian kutipan. Hindari judul provokatif, fitnah, doxing, dan komentar kasar. Ingat bahwa konten yang sudah tersebar dapat sulit ditarik kembali.','Gunakan prinsip: benar → bermanfaat → santun → relevan → bertanggung jawab.'],
  ['10. Proyek kampanye dakwah positif','Buat kelompok kecil dan pilih tema yang dekat dengan kehidupan siswa, misalnya anti-bullying, menjaga kebersihan, adab bermedia sosial, disiplin salat, atau budaya membaca. Buat satu poster, video pendek, atau naskah pesan dakwah.','Uji karya dengan pertanyaan: apakah faktanya benar, bahasanya santun, tidak mempermalukan pihak tertentu, dan mengajak tindakan yang jelas?']
 ],
 hikmah:'Dakwah yang berhikmah membuat kebenaran terasa sebagai jalan perbaikan, bukan alat untuk merendahkan. Pendakwah perlu memadukan ilmu, akhlak, keteladanan, dan keteguhan.'
}
};
