const {createClient}=supabase;const db=createClient(LMS_CONFIG.SUPABASE_URL,LMS_CONFIG.SUPABASE_ANON_KEY);const app=document.getElementById('app');let exams=[],questions=[],attempt=null,index=0,answers={},timer=null,remaining=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function load(){const {data,error}=await db.from('cbt_exams').select('*').eq('is_published',true).order('created_at',{ascending:false});if(error){app.innerHTML='<div class="card"><h2>Gagal memuat</h2><p>'+esc(error.message)+'</p></div>';return}exams=data||[];showHome()}
function showHome(){app.innerHTML='<section class="card"><h2>Penilaian Harian</h2><p class="muted">Silakan pilih penilaian yang tersedia.</p>'+ (exams.length?exams.map(e=>`<div class="exam"><div><h3>${esc(e.title)}</h3><div class="muted">${esc(e.subject)} • Kelas ${esc(e.class_name)} • ${e.duration_minutes} menit</div></div><button onclick="startForm('${e.id}')">Mulai</button></div>`).join(''):'<p>Belum ada Penilaian Harian yang diterbitkan.</p>')+'</section>'}
window.startForm=id=>{const e=exams.find(x=>x.id===id);app.innerHTML=`<section class="card"><h2>${esc(e.title)}</h2><p>${esc(e.instructions||'Kerjakan semua soal dengan teliti.')}</p><div class="grid"><label>Nama Lengkap<input id="nama" autocomplete="name"></label><label>Kelas<input id="kelas" value="${esc(e.class_name)}"></label><label>Nomor Peserta<input id="nomor"></label></div><p><button onclick="begin('${e.id}')">Mulai Penilaian</button> <button class="secondary" onclick="showHome()">Kembali</button></p></section>`};
window.begin=async id=>{const e=exams.find(x=>x.id===id),name=document.getElementById('nama').value.trim(),cls=document.getElementById('kelas').value.trim(),num=document.getElementById('nomor').value.trim();if(!name||!cls||!num){alert('Nama, kelas, dan nomor peserta wajib diisi.');return}const {data:qs,error:qerr}=await db.from('cbt_questions_public').select('*').eq('exam_id',id).order('question_number');if(qerr||!qs?.length){alert('Soal belum tersedia.');return}const attemptId=crypto.randomUUID();const {error}=await db.from('cbt_attempts').insert({id:attemptId,exam_id:id,student_name:name,student_class:cls,participant_number:num,status:'in_progress',total_questions:qs.length});if(error){alert(error.message);return}attempt={id:attemptId,student_name:name};questions=qs;answers={};index=0;remaining=e.duration_minutes*60;renderQuestion();timer=setInterval(()=>{remaining--;renderTimer();if(remaining<=0){clearInterval(timer);submitExam(true)}},1000)};
function renderTimer(){const el=document.getElementById('timer');if(el){const m=Math.floor(remaining/60),s=remaining%60;el.textContent=`Waktu ${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}}
function renderQuestion(){const q=questions[index];app.innerHTML=`<div class="topbar"><span>Soal ${index+1} dari ${questions.length}</span><span id="timer" class="timer"></span></div><section class="card"><div class="qnum">Nomor ${q.question_number}</div><h2>${esc(q.question_text)}</h2>${['a','b','c','d','e'].map(o=>`<label class="option"><input type="radio" name="jawab" value="${o}" ${answers[q.id]===o?'checked':''} onchange="choose('${q.id}','${o}')"> <b>${o.toUpperCase()}.</b> ${esc(q['option_'+o])}</label>`).join('')}<div class="actions"><button class="secondary" onclick="prevQ()" ${index===0?'disabled':''}>Sebelumnya</button>${index===questions.length-1?'<button onclick="submitExam(false)">Kirim Jawaban</button>':'<button onclick="nextQ()">Berikutnya</button>'}</div></section>`;renderTimer()}
window.choose=(qid,o)=>{answers[qid]=o};window.nextQ=()=>{if(index<questions.length-1){index++;renderQuestion()}};window.prevQ=()=>{if(index>0){index--;renderQuestion()}};
window.submitExam=async auto=>{if(!auto&&!confirm('Yakin ingin mengirim jawaban?'))return;clearInterval(timer);for(const q of questions){if(answers[q.id])await db.from('cbt_answers').upsert({attempt_id:attempt.id,question_id:q.id,selected_option:answers[q.id]},{onConflict:'attempt_id,question_id'})}const {data,error}=await db.rpc('submit_cbt_attempt',{p_attempt_id:attempt.id});if(error){alert(error.message);return}app.innerHTML=`<section class="card result"><h2>Penilaian Selesai</h2><p>Terima kasih, ${esc(attempt.student_name)}.</p><div class="score">${data[0].score}</div><p>Nilai Anda</p><p>Jawaban benar: <b>${data[0].correct_count}</b> dari ${data[0].total_questions}</p><button onclick="showHome()">Kembali ke Beranda</button></section>`};load();