const D=LMS_DATA,C=LMS_CONFIG,READY=!!(window.supabase&&C.SUPABASE_URL&&C.SUPABASE_ANON_KEY&&!C.SUPABASE_ANON_KEY.includes("PASTE_")),db=READY?supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null,app=document.getElementById("app");let session=null,profile=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function shell(b){app.innerHTML=`<div class="nav"><button class="btn alt" onclick="home()">🏠 Beranda</button>${session?`<button class="btn alt" onclick="dashboard()">📊 Dashboard</button><button class="btn alt" onclick="profilePage()">👤 Profil</button><button class="btn danger" onclick="logout()">Keluar</button>`:""}</div>${b}<footer>LMS Qur’an Hadis MA Al-Huda • V2.2 • ${READY?"Supabase Online":"Belum terhubung"}</footer>`}
async function boot(){if(!READY)return login();let r=await db.auth.getSession();session=r.data.session;if(session)await loadProfile();home()}
async function loadProfile(){let r=await db.from("profiles").select("*").eq("id",session.user.id).single();if(!r.error)profile=r.data}
function login(){shell(`<section class="loginHero"><div class="loginIntro"><span class="pill">LMS DIGITAL • MA AL-HUDA</span><h1>Belajar Qur’an Hadis<br>Lebih Interaktif</h1><p>Materi, LKPD, kuis, refleksi, dan pemantauan pembelajaran Kelas XII dalam satu LMS.</p><div class="loginFeatures"><button class="featureBtn" onclick="featureAction('chapters')">📚 Bab 1–4</button><button class="featureBtn" onclick="featureAction('lkpd')">📝 LKPD Digital</button><button class="featureBtn" onclick="featureAction('quiz')">🎯 Kuis Otomatis</button><button class="featureBtn" onclick="featureAction('dashboard')">📊 Dashboard</button></div></div><div class="card loginCard"><h2>🔐 Masuk LMS</h2><p class="muted">Silakan pilih jenis akun Anda.</p><div class="loginSection"><h3>👨‍🎓 Login Siswa</h3><label>NIS</label><input id="nis" class="input" inputmode="numeric" placeholder="Contoh: 12345"><label>PIN</label><input id="pin" class="input" type="password" inputmode="numeric" placeholder="PIN siswa"><button class="btn wide" onclick="studentLogin()">Masuk sebagai Siswa →</button></div><hr><div class="loginSection"><h3>👨‍🏫 Login Guru</h3><label>Email Guru</label><input id="gemail" class="input" type="email" placeholder="maalhuda@gmail.com"><label>Password</label><input id="gpass" class="input" type="password" placeholder="Password"><button class="btn alt wide" onclick="teacherLogin()">Masuk sebagai Guru →</button><button class="linkBtn" onclick="resetGuruPassword()">🔑 Lupa Password Guru?</button></div>${!READY?'<p class="notice">⚠️ Supabase belum terhubung. Isi <b>js/config.js</b> dengan Publishable Key.</p>':'<p class="online">● Supabase terhubung</p>'}</div></section>`)}
function featureAction(type){
 if(session){
  if(type==='chapters') return home();
  if(type==='dashboard') return dashboard();
  if(type==='lkpd' || type==='quiz') return alert('Silakan pilih Bab 1–4 terlebih dahulu untuk membuka '+(type==='lkpd'?'LKPD Digital':'Kuis Otomatis')+'.');
 }
 const nis=document.getElementById('nis');
 if(nis){nis.focus();nis.scrollIntoView({behavior:'smooth',block:'center'});}
 alert('Silakan login terlebih dahulu untuk menggunakan fitur ini.');
}
async function resetGuruPassword(){if(!READY)return alert("Konfigurasi Supabase belum diisi.");const email=document.getElementById("gemail").value.trim();if(!email)return alert("Masukkan email Guru terlebih dahulu.");const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+window.location.pathname});if(error)return alert(error.message);alert("Link reset password sudah dikirim ke email Guru. Silakan cek Gmail.")}
async function studentLogin(){if(!READY)return alert("Konfigurasi Supabase belum diisi.");let n=document.getElementById("nis").value.trim(),p=document.getElementById("pin").value;if(!n||!p)return alert("NIS dan PIN wajib diisi.");let r=await db.auth.signInWithPassword({email:`${n}@student.alhuda.local`,password:p});if(r.error)return alert("NIS atau PIN salah.");session=r.data.session;await loadProfile();if(!profile||profile.role!=="student"){await db.auth.signOut();session=null;return alert("Profil siswa belum terhubung.");}home()}
async function teacherLogin(){if(!READY)return alert("Konfigurasi Supabase belum diisi.");let r=await db.auth.signInWithPassword({email:document.getElementById("gemail").value.trim(),password:document.getElementById("gpass").value});if(r.error)return alert(r.error.message);session=r.data.session;await loadProfile();if(!profile||profile.role!=="teacher"){await db.auth.signOut();session=null;return alert("Akun ini bukan guru.");}home()}
async function logout(){if(READY)await db.auth.signOut();session=null;profile=null;login()}
function home(){if(!session)return login();shell(`<section class="card"><h2>Selamat datang, ${esc(profile?.name)}</h2><p>Peran: ${esc(profile?.role)}</p></section><section class="grid">${D.chapters.map(c=>`<article class="card"><span class="pill">BAB ${c.no}</span><h2>${esc(c.title)}</h2><p>${esc(c.fokus)}</p><p><b>${esc(c.dalil)}</b></p><button class="btn" onclick="chapter(${c.no})">Masuk Bab ${c.no}</button></article>`).join("")}</section>`)}
async function chapter(no){let c=D.chapters.find(x=>x.no===no),lk=await getLK(no);shell(`<section class="card"><span class="pill">BAB ${no}</span><h1>${esc(c.title)}</h1><p>${esc(c.fokus)}</p><p><b>Dalil:</b> ${esc(c.dalil)}</p></section><section class="card"><h2>📚 Materi Pembelajaran</h2><p>Materi Bab ${no} disusun lebih lengkap berdasarkan cakupan buku Al-Qur’an Hadis Kelas XII: tujuan, peta konsep, pembahasan dalil, penerapan, dan aktivitas reflektif.</p><button class="btn" onclick="material(${no})">📖 Buka Materi Lengkap</button> <button class="btn alt" onclick="mark(${no},'material_done')">✓ Tandai Materi Selesai</button></section><section class="card"><h2>📝 LKPD</h2><textarea id="lkpd" rows="8" placeholder="Tuliskan jawaban LKPD...">${esc(lk?.answer||"")}</textarea><button class="btn" onclick="submitLK(${no})">Kirim LKPD</button><span id="lkmsg"></span></section><section class="card q"><h2>🎯 Kuis Bab ${no}</h2><div id="quizbox"></div></section>`);runQuiz(no)}
function material(no){let c=D.chapters.find(x=>x.no===no),m=MATERIALS[no];if(!c||!m)return alert('Materi Bab ini belum tersedia.');shell(`<section class="card"><button class="btn alt" onclick="chapter(${no})">← Kembali ke Bab ${no}</button><span class="pill" style="margin-left:8px">MATERI BAB ${no}</span><h1>📖 ${esc(m.judul)}</h1><p>${esc(m.pengantar)}</p><h2>🎯 Tujuan Pembelajaran</h2><ul>${m.tujuan.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>🗺️ Peta Konsep</h2><div class="notice"><b>${esc(m.peta)}</b></div></section>${m.subbab.map(x=>`<section class="card materialSection"><h2>${esc(x[0])}</h2><p>${esc(x[1])}</p><div class="notice"><b>Contoh/Penerapan:</b> ${esc(x[2])}</div></section>`).join('')}<section class="card"><h2>💡 Mutiara Hikmah</h2><p>${esc(m.hikmah)}</p><h3>🧠 Refleksi Akhir</h3><ol><li>Gagasan apa yang paling penting dari bab ini?</li><li>Dalil mana yang paling kuat mengubah cara pandang saya?</li><li>Kebiasaan apa yang akan saya mulai atau perbaiki?</li></ol><button class="btn" onclick="mark(${no},'material_done');chapter(${no})">✓ Selesai Mempelajari Materi</button></section>`)}
async function getLK(no){let r=await db.from("lks_submissions").select("*").eq("student_id",session.user.id).eq("chapter",no).maybeSingle();return r.data}
async function submitLK(no){let a=document.getElementById("lkpd").value.trim();if(!a)return alert("Jawaban belum diisi.");let r=await db.from("lks_submissions").upsert({student_id:session.user.id,chapter:no,answer:a,status:"submitted",updated_at:new Date().toISOString()},{onConflict:"student_id,chapter"});if(r.error)return alert(r.error.message);document.getElementById("lkmsg").textContent=" Terkirim ✓";await mark(no,"lkpd_done")}
async function mark(no,type){let r=await db.from("progress").upsert({student_id:session.user.id,chapter:no,[type]:true,updated_at:new Date().toISOString()},{onConflict:"student_id,chapter"});if(r.error)alert(r.error.message)}
function runQuiz(no){let qs=D.quiz[no],i=0,sc=0,box=document.getElementById("quizbox");function draw(){if(i>=qs.length){box.innerHTML=`<h3>Skor ${sc}/${qs.length}</h3><button class="btn" onclick="saveScore(${no},${sc},${qs.length})">💾 Simpan Nilai</button>`;return}let q=qs[i];box.innerHTML=`<p><b>${i+1}. ${esc(q[0])}</b></p>${q[1].map((o,j)=>`<button onclick="ans(${j})">${esc(o)}</button>`).join("")}`}window.ans=j=>{let q=qs[i],b=box.querySelectorAll("button");if(j===q[2]){sc++;b[j].classList.add("ok")}else{b[j].classList.add("no");b[q[2]].classList.add("ok")}setTimeout(()=>{i++;draw()},450)};draw()}
async function saveScore(no,sc,total){let r=await db.from("quiz_scores").upsert({student_id:session.user.id,chapter:no,score:sc,total,submitted_at:new Date().toISOString()},{onConflict:"student_id,chapter"});if(r.error)return alert(r.error.message);await mark(no,"quiz_done");alert("Nilai tersimpan.")}
async function dashboard(){if(profile?.role==="teacher")return teacher();let r=await db.from("quiz_scores").select("*").eq("student_id",session.user.id),s=r.data||[];shell(`<section class="card"><h2>📊 Dashboard Siswa</h2><table class="table"><tr><th>Bab</th><th>Nilai</th></tr>${D.chapters.map(c=>{let x=s.find(v=>v.chapter===c.no);return `<tr><td>Bab ${c.no}</td><td>${x?Math.round(x.score/x.total*100):"-"}</td></tr>`}).join("")}</table></section>`)}
async function importStudents(){if(profile?.role!=="teacher")return alert("Hanya Guru yang boleh melakukan import.");if(!confirm("Import/sinkronkan 158 siswa dari daftar resmi MA Al-Huda sekarang?"))return;let r=await db.functions.invoke("import-siswa");if(r.error)return alert("Import gagal: "+r.error.message);let x=r.data||{};alert(`Import selesai.\n\nTotal: ${x.total}\nAkun baru: ${x.created}\nDiperbarui: ${x.updated}\nGagal: ${x.failed}`);await teacher()}
async function teacher(){let a=await db.from("profiles").select("*").eq("role","student").order("class_name").order("name"),b=await db.from("quiz_scores").select("*"),l=await db.from("lks_submissions").select("*").order("updated_at",{ascending:false}),students=a.data||[],scores=b.data||[],subs=l.data||[];let rows=students.map(u=>{let v=[1,2,3,4].map(n=>{let s=scores.find(x=>x.student_id===u.id&&x.chapter===n);return s?Math.round(s.score/s.total*100):"-"}),nums=v.filter(x=>x!=="-"),avg=nums.length?Math.round(nums.reduce((x,y)=>x+y,0)/nums.length):"-";return `<tr><td>${esc(u.name)}</td><td>${esc(u.nis||"-")}</td><td>${esc(u.class_name||"-")}</td>${v.map(x=>`<td>${x}</td>`).join("")}<td><b>${avg}</b></td></tr>`}).join("");let lkrows=subs.map(x=>{let st=students.find(u=>u.id===x.student_id);return `<tr><td>${esc(st?.name||x.student_id)}</td><td>${esc(st?.nis||"-")}</td><td>Bab ${esc(x.chapter)}</td><td>${esc(x.status||"submitted")}</td><td>${new Date(x.updated_at||Date.now()).toLocaleString("id-ID")}</td></tr>`}).join("");shell(`<section class="card"><h2>📊 Dashboard Guru</h2><p><b>${students.length}</b> siswa terdaftar • <b>${subs.length}</b> pengumpulan LKPD</p><button class="btn" onclick="importStudents()">👥 Import/Sinkronkan 158 Siswa</button><p class="muted">PIN awal: 6 digit terakhir NIS. Akun Alfira tetap menggunakan PIN 12345.</p><h3>📈 Rekap Nilai Kuis</h3><div style="overflow:auto"><table class="table"><tr><th>Siswa</th><th>NIS</th><th>Kelas</th><th>B1</th><th>B2</th><th>B3</th><th>B4</th><th>Rata-rata</th></tr>${rows||"<tr><td colspan=8>Belum ada siswa.</td></tr>"}</table></div></section><section class="card"><h3>📥 Pengumpulan LKPD Siswa</h3><p>Semua pengumpulan yang tersimpan di Supabase tampil di sini.</p><div style="overflow:auto"><table class="table"><tr><th>Siswa</th><th>NIS</th><th>Bab</th><th>Status</th><th>Waktu</th></tr>${lkrows||"<tr><td colspan=5>Belum ada pengumpulan LKPD.</td></tr>"}</table></div></section>`)}
function profilePage(){shell(`<section class="card"><h2>👤 Profil</h2><p><b>Nama:</b> ${esc(profile?.name)}</p><p><b>NIS:</b> ${esc(profile?.nis||"-")}</p><p><b>Kelas:</b> ${esc(profile?.class_name||"-")}</p><p><b>Peran:</b> ${esc(profile?.role)}</p></section>`)}
boot();